import Head from 'next/head'
import Header from '../components/Header'

function Shared({children}) {
  return (
    <div>
       <Head>
        <title>Baby Steps</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header/>
      {children}
    </div>
  )
}

export default Shared
